// Generated by CoffeeScript 1.6.3
var angTangle, cli, help, nopt, path, pkg, _;

path = require("path");

_ = require("underscore");

nopt = require("nopt");

pkg = require("../package.json");

angTangle = require("./ang-tangle");

cli = exports;

cli.main = function(args) {
  var longOpts, name, opt, opts, parsed, shortOpts, _ref;
  if (args.length === 0) {
    help();
  }
  if ((_ref = args[0]) === "?" || _ref === "-?" || _ref === "--?") {
    help();
  }
  opts = {
    verbose: ["v", Boolean],
    help: ["h", Boolean]
  };
  longOpts = {};
  shortOpts = {};
  for (name in opts) {
    opt = opts[name];
    shortOpts[opt[0]] = "--" + name;
    longOpts[name] = opt[1];
  }
  parsed = nopt(longOpts, shortOpts, args, 0);
  if (parsed.help) {
    help();
  }
  args = parsed.argv.remain;
  opts = _.pick(parsed, _.keys(longOpts));
  if (args.length === 0) {
    help();
  }
  angTangle.run(args, opts);
};

help = function() {
  console.log("" + pkg.name + " [options] input-directory output-file\n\n    input-directory is a directory of files to ang-tangle-ize\n    output-file     is the name of the file to be generated\n\noptions:\n\n    -v --verbose     be verbose\n\nversion: " + pkg.version + "; for more info: " + pkg.homepage);
  return process.exit(1);
};

if (require.main === module) {
  cli.main.call(null, process.argv.slice(2));
}
