// Generated by CoffeeScript 1.6.3
var angTangle, cli, help, nopt, path, pkg, _;

path = require("path");

_ = require("underscore");

nopt = require("nopt");

pkg = require("../package.json");

angTangle = require("./ang-tangle");

cli = exports;

cli.main = function(args) {
  var longOpts, name, opt, opts, parsed, shortOpts, _ref;
  if (args.length === 0) {
    help();
  }
  if ((_ref = args[0]) === "?" || _ref === "-?" || _ref === "--?") {
    help();
  }
  opts = {
    bower: ["b", Boolean],
    copy: ["c", [path]],
    ignore: ["i", [path]],
    output: ["o", path],
    verbose: ["v", Boolean],
    help: ["h", Boolean]
  };
  longOpts = {};
  for (name in opts) {
    opt = opts[name];
    longOpts[name] = opt[1];
  }
  shortOpts = {};
  for (name in opts) {
    opt = opts[name];
    shortOpts[opt[0]] = "--" + name;
  }
  parsed = nopt(longOpts, shortOpts, args, 0);
  if (parsed.help) {
    help();
  }
  args = parsed.argv.remain;
  opts = _.pick(parsed, _.keys(longOpts));
  if (opts.copy == null) {
    opts.copy = [];
  }
  if (opts.ignore == null) {
    opts.ignore = [];
  }
  if (args.length === 0) {
    help();
  }
  angTangle.run(args[0], opts);
};

help = function() {
  console.log("" + pkg.name + " [options] directory\n\ndirectory is a directory of files to ang-tangle-ize\n\noptions:\n\n    -b --bower       re-get bower files based on bower-files module\n    -c --copy dir    copy directory\n    -i --ignore dir  ignore directory\n    -o --output dir  output directory\n    -v --verbose     be verbose\n\nIf you don't specify an output directory, an output directory\nof <directory>-out willl be used.\n\nThe --ignore and --copy options may be used multiple times. \n\nDirectories that are --ignore'd will not be processed or copied into\nthe output directory.\n\nDirectories that are --copy'd will not be processed but will be copied into\nthe output directory.\n\nversion: " + pkg.version + "; for more info: " + pkg.homepage + "    ");
  return process.exit(1);
};

if (require.main === module) {
  cli.main.call(null, process.argv.slice(2));
}
